[project]
name = "rag-researcher"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "langchain",
    "langchain-ollama",
    "pypdf",
    "langchain-community",
    "youtube-transcript-api",
    "transformers",
    "python-dotenv",
    "ipywidgets",
    "sqlalchemy",
    "alembic",
    "psycopg2-binary",
    "pgvector",
    "fastapi",
    "fastapi[standard]",
    "uvicorn[standard]",
    "bcrypt",
    "python-jose[cryptography]",
    "redis[asyncio]>=5.0.0",
    "structlog"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]
