"""File-related helper utilities."""

import uuid
from pathlib import Path
from typing import Optional, Union

from fastapi import UploadFile


def ensure_directory(path: Union[str, Path]) -> Path:
    """Create a directory (and any missing parents) if it does not exist.

    Args:
        path: Directory path to create.

    Returns:
        Path: Resolved ``Path`` object for the created/existing directory.
    """
    target = Path(path)
    target.mkdir(parents=True, exist_ok=True)
    return target


def generate_unique_filename(original_name: str) -> str:
    """Generate a UUID4-based filename that preserves the original extension.

    Args:
        original_name: Original filename whose extension is kept.

    Returns:
        str: Filename in the form ``"{uuid_hex}{ext}"``.
    """
    return f"{uuid.uuid4().hex}{suffix}"


def validate_pdf_upload(file: UploadFile, max_bytes: int = 20 * 1024 * 1024) -> None:
    """Validate that an uploaded file is a PDF and within the size limit.

    Checks the filename extension, MIME content type, and file size.  The
    file descriptor seek position is preserved after the size check.

    Args:
        file: FastAPI ``UploadFile`` from a multipart form request.
        max_bytes: Maximum allowed file size in bytes (default 20 MB).

    Raises:
        ValueError: If the file is not a PDF, has an invalid content type,
            or exceeds ``max_bytes``.
    """

    if not file.filename or Path(file.filename).suffix.lower() != ".pdf":
        raise ValueError("Only PDF files are accepted")

    if file.content_type not in {"application/pdf", "application/x-pdf"}:
        raise ValueError("Invalid content type for PDF upload")

    pos = file.file.tell()
    file.file.seek(0, 2)
    size = file.file.tell()
    file.file.seek(pos)

    if size > max_bytes:
        raise ValueError("File exceeds maximum allowed size")


def save_upload_file(
    file: UploadFile,
    upload_dir: Union[str, Path],
    *,
    filename: Optional[str] = None,
) -> Path:
    """Save an ``UploadFile`` to disk and return its path.

    Reads the file in 1 MB chunks to avoid loading large PDFs into memory.
    The destination directory is created automatically via
    :func:`ensure_directory`.

    Args:
        file: FastAPI ``UploadFile`` from a multipart form request.
        upload_dir: Directory to write the file into.
        filename: Override the generated filename.  If omitted, a
            UUID4-based name is generated by :func:`generate_unique_filename`.

    Returns:
        Path: Absolute path to the saved file.
    """

    target_name = filename or generate_unique_filename(file.filename or "upload")
    target_path = Path(upload_dir) / target_name

    with target_path.open("wb") as out:
        while True:
            chunk = file.file.read(1024 * 1024)
            if not chunk:
                break
            out.write(chunk)

    return target_path
