"""add source identity fields

Revision ID: 6cbf24872409
Revises: c42711e73bd6
Create Date: 2026-02-02 21:18:40.063293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbf24872409'
down_revision: Union[str, Sequence[str], None] = 'c42711e73bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_key', sa.String(length=512), nullable=True))
    op.add_column('sources', sa.Column('source_uri', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('sources', sa.Column('content_hash', sa.String(length=128), nullable=True))
    op.add_column('sources', sa.Column('last_ingested_at', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'updated_at')
    op.drop_column('sources', 'last_ingested_at')
    op.drop_column('sources', 'content_hash')
    op.drop_column('sources', 'external_id')
    op.drop_column('sources', 'source_uri')
    op.drop_column('sources', 'source_key')
    # ### end Alembic commands ###
